import hudson.model.*

node {
  // The last stage cleans up the local images and workspace
  stage('Housekeeping') {
    deleteDir()
  }

  // The first stage checks out the code from Github
  stage('Get Code') {
    checkout scm
  }

  // Creating instances
  stage('Build Virtual Machines') {
    dir('preparation/test') {
      sh 'chmod 600 ansible_key'
      sh 'ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -vvv -i ansible_hosts -s --private-key=ansible_key create_instances.yaml'
    }
  }

  // Pre-configuration
  stage('Preparation Stage') {
    dir('preparation/test') {
      sh 'chmod 600 ansible_key'
      sh 'ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -vvv -i ansible_hosts -u root --private-key=ansible_key pre-configuration.yaml'
    }
  }
}

