node {
  // The last stage cleans up the local images and workspace
  stage('Housekeeping') {

    deleteDir()
    sh 'env > env.txt'
    readFile('env.txt').split("\r?\n").each {
        println it
    }
  }

  // The first stage checks out the code from Github
  stage 'Get Code'

  // Get some code from a GitHub repository
  checkout scm


}

