heat_template_version: 2018-08-31

description: Creating Handson image

resources:
  secg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: open-all
      rules:
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: tcp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0

  private_network:
    type: OS::Neutron::Net
    properties:
      name: build-net

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: build-subnet
      ip_version: 4
      network_id: { get_resource: private_network }
      cidr: 192.168.188.0/24
      gateway_ip: 192.168.188.254
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4

  ext_router:
    type: OS::Neutron::Router
    properties:
      name: Build-Router
      external_gateway_info:
        network: public

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: ext_router }
      subnet_id: { get_resource: private_subnet }

  key_pair:
    type: OS::Nova::KeyPair
    properties:
      name: key-for-build
      save_private_key: true

outputs:
  base_env:
    description: console server information
    value:
      private_key: { get_attr: [ key_pair, private_key ] }
