heat_template_version: 2018-08-31

description: Setup default environment.

parameters:
  passwd:
    type: string
    default: topse2023

resources:
  public:
    type: OS::Neutron::ProviderNet
    properties:
      name: public
      network_type: flat
      physical_network: extnet
      router_external: True

  public-subnet:
    type: OS::Neutron::Subnet
    properties:
      name: public-subnet
      allocation_pools:
        - start: 157.1.141.101
          end: 157.1.141.200
      cidr: 157.1.140.0/23
      enable_dhcp: False
      gateway_ip: 157.1.140.1
      ip_version: 4
      network: { get_resource: public }

  pj-topse01:
    type: OS::Keystone::Project
    properties:
      name: topse01

  pj-topse02:
    type: OS::Keystone::Project
    properties:
      name: topse02

  role-teacher:
    type: OS::Keystone::Role
    properties:
      domain: default
      name: teacher

  role-student:
    type: OS::Keystone::Role
    properties:
      domain: default
      name: student

  user-teacher01:
    type: OS::Keystone::User
    properties:
      name: teacher01
      default_project: { get_resource: pj-topse01 }
      password: { get_param: passwd }
      roles:
        - role: { get_resource: role-teacher }
          project: { get_resource: pj-topse01 }
        - role: SwiftOperator
          project: { get_resource: pj-topse01 }
        - role: heat_stack_owner
          project: { get_resource: pj-topse01 }

  user-teacher02:
    type: OS::Keystone::User
    properties:
      name: teacher02
      default_project: { get_resource: pj-topse02 }
      password: { get_param: passwd }
      roles:
        - role: { get_resource: role-teacher }
          project: { get_resource: pj-topse02 }
        - role: SwiftOperator
          project: { get_resource: pj-topse02 }
        - role: heat_stack_owner
          project: { get_resource: pj-topse02 }
