heat_template_version: 2015-04-30

description: launch multiple servers for ansible automation

parameters:
  private_network:
    type: string
    label: Internal network name
    description: Internal network name or ID
    default: work-net

  sec_group:
    type: string
    label: Security group name
    description: Security group name
    default: open-all

  key:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
    default: key-for-console

  image:
    type: string
    default: CentOS8

  flavor:
    type: string
    default: m1.tiny

  cluster_size:
    type: string
    default: 3

resources:
  server:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: cluster_size }
      resource_def:
        type: OS::Nova::Server
        properties:
          image: { get_param: image }
          key_name: { get_param: key }
          flavor: { get_param: flavor }
          networks:
            - network: { get_param: private_network }
          security_groups:
            - { get_param: sec_group }
          user_data_format: RAW
          user_data: { get_resource: server_init }

  wait_handle:
    type: OS::Heat::WaitConditionHandle

  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: { get_resource: wait_handle }
      count: { get_param: cluster_size }
      timeout: 600

  config_send_notify_after_settings:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          params:
            __heat_wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }
          template: |
            #!/bin/bash -ex
            __heat_wc_notify --data-binary '{"status": "SUCCESS"}'

  server_init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: { get_resource: config_send_notify_after_settings }

