- name: create vms for openstack
  hosts: localhost
  tasks:
  - name: The preparation /tmp/simple-cent7-ks-xxx.cfg before creating vms
    template: >
      src=utils/simple-centos7-ks.cfg.2
      dest=/tmp/simple-centos7-ks-{{ item["host"] }}.cfg
    when:
      - reposerver_ip is defined
      - ansible_key_pub is defined
      - gateway is defined
      - dns_server is defined
      - item["ip"] is defined
    with_items: "{{ rdo_hosts }}"

  - name: create vms
    shell: |
      qemu-img create -f qcow2 /var/lib/libvirt/images/test-{{ item['host'] }}.qcow2 500G
      sleep 2
      virt-install \
      --name=test-"{{ item['host'] }}" \
      --virt-type kvm --hvm \
      --accelerate \
      --nographics --noautoconsole \
      --vcpus=8 \
      --ram=24576 \
      --cpu host \
      --disk /var/lib/libvirt/images/test-"{{ item['host'] }}".qcow2,format=qcow2 \
      --network network=virbr100 \
      --location=http://{{ reposerver_ip }}/dvd/ \
      --initrd-inject simple-centos7-ks-"{{ item['host'] }}".cfg \
      --extra-args='inst.ks=file:/simple-centos7-ks-{{ item["host"] }}.cfg console=tty0 console=ttyS0,115200n8 serial'
    args:
      chdir: /tmp
    with_items:  "{{ rdo_hosts }}"

  - name: waiting to finish install
    shell: |
      RET=0
      while [ "$RET" = "0" ]
      do
         virsh list | grep test-rdo
         RET=$?
         sleep 5
      done

  - name: start instances
    shell: |
      virsh start test-rdo-cc
      virsh start test-rdo-compute1
      virsh start test-rdo-compute2
      exit 0
