heat_template_version: 2015-04-30

description: Setup default environment.

parameters:
  public_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: public

resources:
  console_server_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: sg-for-tools
      rules:
        - protocol: icmp
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          port_range_min: 3389
          port_range_max: 3389

  private_network:
    type: OS::Neutron::Net
    properties:
      name: tools-net

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: tools-subnet
      ip_version: 4
      network_id: { get_resource: private_network }
      cidr: 10.99.99.0/24
      gateway_ip: 10.99.99.254
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4

  ext_router:
    type: OS::Neutron::Router
    properties:
      name: Ext-Router
      external_gateway_info:
        network: { get_param: public_network }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: ext_router }
      subnet_id: { get_resource: private_subnet }

