- name: OpenStack Installation
  hosts: openstack-cc
  tasks:
  - name: install openstack-packstack
    yum: name=openstack-packstack state=latest

  - name: create answer file
    shell: |
      packstack --dry-run --allinone --default-password='{{ password }}' --provision-demo=n --gen-answer-file=/root/answer.txt

  - set_fact:
      cc_host: "{{ hostvars[inventory_hostname]['groups']['openstack-cc'] | join(',') }}"
      nw_host: "{{ hostvars[inventory_hostname]['groups']['openstack-cc'] | join(',') }}"
      com_hosts: "{{ hostvars[inventory_hostname]['groups']['openstack-compute'] | join(',') }}"

  - name: edit answer file
    shell: |
      crudini --set /root/answer.txt general CONFIG_NAGIOS_INSTALL y
      crudini --set /root/answer.txt general CONFIG_CEILOMETER_INSTALL n
      crudini --set /root/answer.txt general CONFIG_SWIFT_INSTALL y
      crudini --set /root/answer.txt general CONFIG_HEAT_INSTALL y

      crudini --set /root/answer.txt general CONFIG_CONTROLLER_HOST {{ cc_host }}
      crudini --set /root/answer.txt general CONFIG_NETWORK_HOSTS   {{ nw_host }}
      crudini --set /root/answer.txt general CONFIG_COMPUTE_HOSTS   {{ com_hosts }}

      crudini --set /root/answer.txt general CONFIG_KEYSTONE_REGION RegionOne
      crudini --set /root/answer.txt general CONFIG_CINDER_VOLUMES_SIZE {{ cinder_size }}
      crudini --set /root/answer.txt general CONFIG_SWIFT_STORAGE_SIZE {{ swift_size }}

      crudini --set /root/answer.txt general CONFIG_NEUTRON_ML2_TYPE_DRIVERS vxlan,flat
      crudini --set /root/answer.txt general CONFIG_NEUTRON_ML2_TENANT_NETWORK_TYPES vxlan
      crudini --set /root/answer.txt general CONFIG_NEUTRON_L3_EXT_BRIDGE br-ex
      crudini --set /root/answer.txt general CONFIG_LBAAS_INSTALL y
      crudini --set /root/answer.txt general CONFIG_NEUTRON_OVS_BRIDGE_MAPPINGS physnet1:br-ex
      crudini --set /root/answer.txt general CONFIG_NEUTRON_OVS_TUNNEL_IF {{ tunn_nic }}
    args:
      removes: /root/answer.txt

- name: temporary disable selinux before run packstack
  hosts: openstack-all
  tasks:
  - name: setenforce 0
    shell: setenforce 0; exit 0
    ignore_errors: True

  - name: install openstack-config command
    yum: name=openstack-utils state=latest

- name: exec packstack
  hosts: openstack-cc
  tasks:
  - name: exec packstack
    shell: |
      packstack --answer-file=/root/answer.txt

  - set_fact:
      cc_host: "{{ hostvars[inventory_hostname]['groups']['openstack-cc'] | join(',') }}"

  - name: edit nova.conf
    shell: |
      openstack-config --set /etc/nova/nova.conf DEFAULT api_rate_limit false
      openstack-config --set /etc/nova/nova.conf DEFAULT novncproxy_host 0.0.0.0
      openstack-config --set /etc/nova/nova.conf DEFAULT novncproxy_port 6080
      openstack-config --set /etc/nova/nova.conf vnc enabled true
      openstack-config --set /etc/nova/nova.conf vnc novncproxy_base_url http://{{ cc_host }}:6080/vnc_auto.html
      openstack-config --set /etc/nova/nova.conf vnc vncserver_listen 0.0.0.0
      openstack-config --set /etc/nova/nova.conf vnc vncserver_proxyclient_address {{ cc_host }}
      openstack-config --set /etc/nova/nova.conf vnc vnc_keymap ja
      openstack-config --set /etc/nova/nova.conf DEFAULT cpu_allocation_ratio 32
      openstack-config --set /etc/nova/nova.conf DEFAULT ram_allocation_ratio 5
      openstack-config --set /etc/nova/nova.conf DEFAULT disk_allocation_ratio 3
      openstack-config --set /etc/nova/nova.conf DEFAULT allow_resize_to_same_host true
    args:
      removes: /etc/nova/nova.conf

  - name: edit cinder.conf
    shell: |
      openstack-config --set /etc/cinder/cinder.conf lvm volume_clear none
    args:
      removes: /etc/cinder/cinder.conf

  - name: edit neutron plugin.ini
    shell: |
      openstack-config --set /etc/neutron/plugin.ini ml2_type_vxlan vni_ranges 10:1000
    args:
      removes: /etc/neutron/plugin.ini

  - name: modify eth0
    template: >-
      src=utils/ifcfg-{{ tunn_nic }}.cfg.j2
      dest=/etc/sysconfig/network-scripts/ifcfg-{{ tunn_nic }}
      owner=root
      group=root
      mode=0644
    when:
      - tunn_nic is defined

  - name: modify br-ex
    template: >-
      src=utils/ifcfg-br-ex-{{ tunn_nic }}.cfg.j2
      dest=/etc/sysconfig/network-scripts/ifcfg-br-ex
      owner=root
      group=root
      mode=0644
    when:
      - tunn_nic is defined

- name: edit openstack conf files on compute node
  hosts: openstack-compute
  tasks:

  - set_fact:
      cc_host: "{{ hostvars[inventory_hostname]['groups']['openstack-cc'] | join(',') }}"

  - name: edit nova.conf
    shell: |
      openstack-config --set /etc/nova/nova.conf vnc enabled true
      openstack-config --set /etc/nova/nova.conf vnc novncproxy_base_url http://{{ cc_host }}:6080/vnc_auto.html
      openstack-config --set /etc/nova/nova.conf vnc vncserver_listen 0.0.0.0
      openstack-config --set /etc/nova/nova.conf vnc vncserver_proxyclient_address {{ inventory_hostname }}
      openstack-config --set /etc/nova/nova.conf vnc vnc_keymap ja
      openstack-config --set /etc/nova/nova.conf libvirt virt_type kvm
      openstack-config --set /etc/nova/nova.conf libvirt cpu_mode host-passthrough
      openstack-config --set /etc/nova/nova.conf DEFAULT cpu_allocation_ratio 32
      openstack-config --set /etc/nova/nova.conf DEFAULT ram_allocation_ratio 5
      openstack-config --set /etc/nova/nova.conf DEFAULT disk_allocation_ratio 3
      openstack-config --set /etc/nova/nova.conf DEFAULT allow_resize_to_same_host true
    args:
      removes: /etc/nova/nova.conf

- name: allow login to nova user
  hosts: openstack-all
  tasks:
  - name: usermod
    shell: usermod -s /bin/bash nova

  - name: copy ssh_config
    copy:
      src: utils/ssh_config
      dest: /var/lib/nova/.ssh/config
      owner: nova
      group: nova
      mode: 0644
