- name: delete all vms
  hosts: localhost

  roles:
  - debug_vars

  tasks:
  - name: cleanup existing vms
    shell: |
      virsh destroy  test-{{ item["host"] }}
      sleep 3
      virsh undefine test-{{ item["host"] }} --remove-all-storage
      sleep 3
      exit 0
    with_items: "{{ rdo_hosts }}"
