---
- import_playbook: 10_test_connection.yaml
- import_playbook: 20_requirements.yaml
- import_playbook: reboot.yaml
- import_playbook: 40_test_requiremetns.yaml
- import_playbook: 50_packstack.yaml
- import_playbook: 60_openstack-config.yaml
- import_playbook: reboot.yaml
