---
# tasks file for /Users/t-nakajima/temp/topse-tools/preparation/roles/wait_boot
- name: wait for SSH port up
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10 timeout=300

- name: ping
  ping:
