- name: Pre-settings for hands-on env
  hosts: allnode
  vars:
    reposerver_ip: 157.1.205.1
  tasks:
    - name: reposerver ip to hosts file
      lineinfile: >
        dest=/etc/hosts
        line='{{ reposerver_ip }} reposerver'

    - name: set repositry
      shell: |
        mkdir -p /root/temp
        mv /etc/yum.repos.d/* /root/temp
        curl -o /etc/yum.repos.d/edubase.repo http://reposerver/openstack/repo/centos7/edubase-kilo.repo
        yum clean all
        yum repolist
      args:
        creates: /etc/yum.repos.d/edubase.repo

    - name: install wget
      yum: name=wget state=latest

    - name: install crudini
      yum: name=crudini state=latest

    - name: install vim
      yum: name=vim state=latest

    - name: update all packages
      yum: name=* state=latest

    - name: clean repo
      shell: |
        rm -f /etc/yum.repos.d/CentOS*
        rm -f /etc/yum.repos.d/epel*

    - name: enable nested kvm
      shell: |
        echo "options kvm_intel nested=1" > /etc/modprobe.d/kvm-nested.conf
        modprobe -r kvm_intel
        modprobe kvm_intel
      args:
        creates: /etc/modprobe.d/kvm-nested.conf

    - name: enable ip forwarding
      template: >
        src=template_00-system.conf
        dest=/usr/lib/sysctl.d/00-system.conf
        owner=root
        group=root
        mode=0644

    - name: create dirs
      shell: |
        mkdir -p /mnt/{nova,glance,cinder,swift}
        mkdir -p /var/lib/{nova,glance,cinder}
        mkdir -p /srv

    - name: add mount point nova
      lineinfile: >
        dest=/etc/fstab
        line='/mnt/nova    /var/lib/nova    none  bind   0 0'

    - name: add mount point glance
      lineinfile: >
        dest=/etc/fstab
        line='/mnt/glance  /var/lib/glance  none  bind   0 0'

    - name: add mount point cinder
      lineinfile: >
        dest=/etc/fstab
        line='/mnt/cinder  /var/lib/cinder  none  bind   0 0'

    - name: add mount point swift
      lineinfile: >
        dest=/etc/fstab
        line='/mnt/swift   /srv             none  bind   0 0'
