- name: edit openstack conf files on controller node
  hosts: controller
  vars:
    ctl_host: 157.1.205.2
  tasks:
    - name: edit nova.conf
      shell: |
        openstack-config --set /etc/nova/nova.conf DEFAULT api_rate_limit false
        openstack-config --set /etc/nova/nova.conf DEFAULT vnc_enabled true
        openstack-config --set /etc/nova/nova.conf DEFAULT novncproxy_host 0.0.0.0
        openstack-config --set /etc/nova/nova.conf DEFAULT novncproxy_port 6080
        openstack-config --set /etc/nova/nova.conf DEFAULT novncproxy_base_url http://{{ ctl_host }}:6080/vnc_auto.html
        openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_listen 0.0.0.0
        openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_proxyclient_address {{ ctl_host }}
        openstack-config --set /etc/nova/nova.conf DEFAULT vnc_keymap ja
        openstack-config --set /etc/nova/nova.conf DEFAULT cpu_allocation_ratio 32
        openstack-config --set /etc/nova/nova.conf DEFAULT ram_allocation_ratio 5
        openstack-config --set /etc/nova/nova.conf DEFAULT disk_allocation_ratio 3
        openstack-config --set /etc/nova/nova.conf DEFAULT allow_resize_to_same_host true
      args:
        removes: /etc/nova/nova.conf

    - name: edit cinder.conf
      shell: |
        openstack-config --set /etc/cinder/cinder.conf lvm volume_clear none
      args:
        removes: /etc/cinder/cinder.conf



- name: edit openstack conf files on compute node
  hosts: compute
  vars:
    ctl_host: 157.1.205.2
  tasks:
    - name: edit nova.conf
      shell: |
        openstack-config --set /etc/nova/nova.conf DEFAULT vnc_enabled true
        openstack-config --set /etc/nova/nova.conf DEFAULT novncproxy_base_url http://{{ ctl_host }}:6080/vnc_auto.html
        openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_listen 0.0.0.0
        openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_proxyclient_address {{ ansible_eth2.ipv4.address }}
        openstack-config --set /etc/nova/nova.conf DEFAULT vnc_keymap ja
        openstack-config --set /etc/nova/nova.conf libvirt virt_type kvm
        openstack-config --set /etc/nova/nova.conf libvirt cpu_mode host-passthrough
        openstack-config --set /etc/nova/nova.conf DEFAULT cpu_allocation_ratio 32
        openstack-config --set /etc/nova/nova.conf DEFAULT ram_allocation_ratio 5
        openstack-config --set /etc/nova/nova.conf DEFAULT disk_allocation_ratio 3
        openstack-config --set /etc/nova/nova.conf DEFAULT allow_resize_to_same_host true
      args:
        removes: /etc/nova/nova.conf


- name: modify eth2 / br-ex files to connect external network
  hosts: controller
  tasks:
    - name: modify eth2 / br-ex files
      script: script_connect_br_to_eth.sh
      args:
        removes: /etc/sysconfig/network-scripts/ifcfg-eth2

