heat_template_version: 2015-04-30

description: Setup default environment.

parameters:
  public_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: public

  ext_router_name:
    type: string
    label: Public router name or ID
    description: Public router which is connected to external network.
    default: Ext-Router

  sec_group:
    type: string
    label: Security group name
    description: Security group name.
    default: open-all

  private_network_name:
    type: string
    label: Private network name
    default: work-net

  private_subnet_name:
    type: string
    label: Private subnet name
    default: work-subnet

  private_subnet_cidr:
    type: string
    label: Private subnet cidr
    default: 192.168.199.0/24

  private_subnet_gw:
    type: string
    label: Private subnet gw ip
    default: 192.168.199.254

resources:
  secg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: open-all
      rules:
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: tcp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0

  private_network:
    type: OS::Neutron::Net
    properties:
      name: work-net

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: work-subnet
      ip_version: 4
      network_id: { get_resource: private_network }
      cidr: 192.168.199.0/24
      gateway_ip: 192.168.199.254
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4

  ext_router:
    type: OS::Neutron::Router
    properties:
      name: Ext-Router
      external_gateway_info:
        network: public

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: ext_router }
      subnet_id: { get_resource: private_subnet }
