- name: prepare packstack answer file
  hosts: openstack-cc
  gather_facts: yes
  max_fail_percentage: 0
  vars:
    password: password
    cc_host: 192.168.199.200
    nw_host: 192.168.199.200
    com_hosts: 192.168.199.201,192.168.199.202
    cinder_size: 20G
    swift_size: 5G
    tunn_nic: eth0

  tasks:
  - name: create answer file
    shell: |
      packstack --dry-run --allinone --default-password='{{ password }}' --provision-demo=n --gen-answer-file=/root/answer.txt

  - name: edit answer file
    shell: |
      crudini --set /root/answer.txt general CONFIG_NAGIOS_INSTALL n
      crudini --set /root/answer.txt general CONFIG_CEILOMETER_INSTALL n
      crudini --set /root/answer.txt general CONFIG_SWIFT_INSTALL y
      crudini --set /root/answer.txt general CONFIG_HEAT_INSTALL y

      crudini --set /root/answer.txt general CONFIG_CONTROLLER_HOST {{ cc_host }}
      crudini --set /root/answer.txt general CONFIG_NETWORK_HOSTS   {{ nw_host }}
      crudini --set /root/answer.txt general CONFIG_COMPUTE_HOSTS   {{ com_hosts }}

      crudini --set /root/answer.txt general CONFIG_KEYSTONE_REGION RegionOne
      crudini --set /root/answer.txt general CONFIG_CINDER_VOLUMES_SIZE {{ cinder_size }}
      crudini --set /root/answer.txt general CONFIG_SWIFT_STORAGE_SIZE {{ swift_size }}

      crudini --set /root/answer.txt general CONFIG_NEUTRON_ML2_TYPE_DRIVERS vxlan,flat
      crudini --set /root/answer.txt general CONFIG_NEUTRON_ML2_TENANT_NETWORK_TYPES vxlan
      crudini --set /root/answer.txt general CONFIG_NEUTRON_L3_EXT_BRIDGE br-ex
      crudini --set /root/answer.txt general CONFIG_LBAAS_INSTALL y
      crudini --set /root/answer.txt general CONFIG_NEUTRON_OVS_BRIDGE_MAPPINGS extnet1:br-ex
      crudini --set /root/answer.txt general CONFIG_NEUTRON_OVS_TUNNEL_IF {{ tunn_nic }}
    args:
      removes: /root/answer.txt

- name: temporary disable selinux before run packstack
  hosts: all
  tasks:
  - name: setenforce 0
    shell: setenforce 0; exit 0
    ignore_errors: True

- name: exec packstack
  hosts: openstack-cc
  tasks:
  - name: exec packstack
    shell: |
      packstack --answer-file=/root/answer.txt

- name: configure cc after packstack
  hosts: openstack-cc
  vars:
    cc_host: 192.168.199.200
  tasks:
  - name: edit nova.conf
    shell: |
      openstack-config --set /etc/nova/nova.conf DEFAULT api_rate_limit false
      openstack-config --set /etc/nova/nova.conf DEFAULT novncproxy_host 0.0.0.0
      openstack-config --set /etc/nova/nova.conf DEFAULT novncproxy_port 6080
      openstack-config --set /etc/nova/nova.conf vnc enabled true
      openstack-config --set /etc/nova/nova.conf vnc novncproxy_base_url http://{{ cc_host }}:6080/vnc_auto.html
      openstack-config --set /etc/nova/nova.conf vnc vncserver_listen 0.0.0.0
      openstack-config --set /etc/nova/nova.conf vnc vncserver_proxyclient_address {{ cc_host }}
      openstack-config --set /etc/nova/nova.conf vnc vnc_keymap ja
      openstack-config --set /etc/nova/nova.conf DEFAULT cpu_allocation_ratio 32
      openstack-config --set /etc/nova/nova.conf DEFAULT ram_allocation_ratio 5
      openstack-config --set /etc/nova/nova.conf DEFAULT disk_allocation_ratio 3
      openstack-config --set /etc/nova/nova.conf DEFAULT allow_resize_to_same_host true
    args:
      removes: /etc/nova/nova.conf

  - name: edit cinder.conf
    shell: |
      openstack-config --set /etc/cinder/cinder.conf lvm volume_clear none
    args:
      removes: /etc/cinder/cinder.conf

  - name: edit neutron plugin.ini
    shell: |
      openstack-config --set /etc/neutron/plugin.ini ml2_type_vxlan vni_ranges 10:1000
    args:
      removes: /etc/neutron/plugin.ini

- name: edit openstack conf files on compute node
  hosts: openstack-compute
  vars:
    cc_host: 192.168.199.200

  tasks:
  - name: edit nova.conf
    shell: |
      openstack-config --set /etc/nova/nova.conf vnc enabled true
      openstack-config --set /etc/nova/nova.conf vnc novncproxy_base_url http://{{ cc_host }}:6080/vnc_auto.html
      openstack-config --set /etc/nova/nova.conf vnc vncserver_listen 0.0.0.0
      openstack-config --set /etc/nova/nova.conf vnc vncserver_proxyclient_address {{ inventory_hostname }}
      openstack-config --set /etc/nova/nova.conf vnc vnc_keymap ja
      openstack-config --set /etc/nova/nova.conf libvirt virt_type kvm
      openstack-config --set /etc/nova/nova.conf libvirt cpu_mode host-passthrough
      openstack-config --set /etc/nova/nova.conf DEFAULT cpu_allocation_ratio 32
      openstack-config --set /etc/nova/nova.conf DEFAULT ram_allocation_ratio 5
      openstack-config --set /etc/nova/nova.conf DEFAULT disk_allocation_ratio 3
      openstack-config --set /etc/nova/nova.conf DEFAULT allow_resize_to_same_host true
    args:
      removes: /etc/nova/nova.conf

- name: allow login to nova user
  hosts: all
  tasks:
  - name: usermod
    shell: usermod -s /bin/bash nova

  - name: copy ssh_config
    copy:
      src: utils/ssh_config
      dest: /var/lib/nova/.ssh/config
      owner: nova
      group: nova
      mode: 0644

- name: allow login to nova user
  hosts: all
  tasks:
    - name: reboot!
      shell: sleep 2 && shutdown -r now "Ansible reboot this host"
      async: 1
      poll: 0
      ignore_errors: true

    - name: wait for SSH port down
      local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped

    - name: wait for SSH port up
      local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10 timeout=300

    - name: test connection (after reboot)
      ping:
