heat_template_version: 2015-10-15

description: A Group of Load Balanced Servers

parameters:
  flavor:
    type: string
    default: m1.tiny
    description: Flavor used for servers
    constraints:
    - custom_constraint: nova.flavor
  image:
    type: string
    default: CentOS7
    description: Image used for servers
    constraints:
    - custom_constraint: glance.image
  private_network:
    type: string
    default: heat-handson-net
    description: Network used by the servers
    constraints:
    - custom_constraint: neutron.network
  sec_group:
    type: string
    description: Security Group used by the server
    default: sg-for-heat
  key:
    type: string
    default: heat-key
  cluster_size:
    type: string
    default: 3
  reposerver:
    type: string
    label: hands-on repository server
    description: Teahcer will give the specific ip address.

resources:
  web_cluster:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: cluster_size }
      resource_def:
        type: 13_option1_single_server.yaml
        properties:
          image: { get_param: image }
          key: { get_param: key }
          flavor: { get_param: flavor }
          private_network: { get_param: private_network }
          sec_group: { get_param: sec_group }
          reposerver: { get_param: reposerver }

outputs:
  instance_ips:
    description: The IP address of the deployed instance
    value: { get_attr: [ web_cluster, server_ip ] }
