- name: launch a compute instance
  hosts: localhost
  vars:
    cloud_auth: topse01
    instance_name: ansible-eplite
  tasks:
  - name: regist my local public keypair
    os_keypair:
      state: present
      cloud: "{{ cloud_auth }}"
      name: key-from-ansible
      public_key_file: /root/.ssh/id_rsa.pub
  - name: launch an instance
    os_server:
      state: present
      cloud: "{{ cloud_auth }}"
      name: "{{ instance_name }}"
      image: CentOS7-Docker
      key_name: key-from-ansible
      timeout: 200
      flavor: m1.small
      security_groups: open_all
      nics:
      - net-name: work-net
      auto_ip: no

- name: create in-memory inventory
  hosts: localhost
  vars:
    cloud_auth: topse01
    instance_name: ansible-*
  tasks:
  - name: retrieve server information
    os_server_facts: 
      cloud: "{{ cloud_auth }}"
      server: "{{ instance_name }}"
    register: eplite
  - name: add host to inventory
    add_host:
      name: "{{ item['private_v4'] }}"
      groups: eplite
    with_items:
    - "{{ eplite['ansible_facts']['openstack_servers'] }}"
  - name: wait insntace boot
    wait_for:
      host: "{{ item['private_v4'] }}"
      port: 22
      state: started
      delay: 30
    with_items:
    - "{{ eplite['ansible_facts']['openstack_servers'] }}"

- name: setup eplite with docker
  hosts: eplite
  remote_user: centos
  vars:
      env:
        FIP: "{{ ansible_eth0.ipv4.address }}"
  tasks:
  - name: checking conectivity
    ping:
  - name: get remote host ip address
    command: echo {{ ansible_eth0.ipv4.address }}
