- name: launch a compute instance
  hosts: localhost
  vars:
    cloud_auth: topse01
    instance_name: ansible-eplite
  tasks:
  - name: regist my local public keypair
    os_keypair:
      state: present
      cloud: "{{ cloud_auth }}"
      name: key-from-ansible
      public_key_file: /root/.ssh/id_rsa.pub
  - name: launch an instance
    os_server:
      state: present
      cloud: "{{ cloud_auth }}"
      name: "{{ instance_name }}"
      image: CentOS7-Docker
      key_name: key-from-ansible
      timeout: 200
      flavor: m1.small
      security_groups: open_all
      nics:
      - net-name: work-net
      auto_ip: no

