heat_template_version: 2015-04-30

description: building heat hands-on env.

parameters:
  private_network:
    type: string
    label: Internal network name
    description: Internal network name or ID
    default: heat-handson-net

  private_subnet:
    type: string
    label: Internal network name
    description: Internal sub-network name or ID
    default: heat-handson-subnet

  private_cidr:
    type: string
    label: Internal network name
    description: Internal sub-network CIDR
    default: 10.20.99.0/24

  private_gw:
    type: string
    label: Gateway IP of internal network
    description: Gateway IP Address
    default: 10.20.99.254

  sec_group:
    type: string
    label: Security group name
    description: Security group name
    default: sg-for-heat

  key:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
    default: heat-key

  ext_router:
    type: string
    label: Public router name or ID
    description: Public router which is connected to external network.
    default: Ext-Router

resources:
  network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_network }

  subnet:
    type: OS::Neutron::Subnet
    properties:
      name: { get_param: private_subnet }
      ip_version: 4
      network_id: { get_resource: network }
      cidr: { get_param: private_cidr }
      gateway_ip: { get_param: private_gw }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_param: ext_router }
      subnet: { get_resource: subnet }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { get_param: sec_group }
      rules:
        - protocol: icmp
        - protocol: tcp
          port_range_min: 1
          port_range_max: 65535
        - protocol: udp
          port_range_min: 1
          port_range_max: 65535

  key_pair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: key }
      save_private_key: true

outputs:
  private_key:
    description: Private Key of generated keypair
    value: { get_attr: [key_pair, private_key] }
