- name: Createing default env
  hosts: openstack-single
  gather_facts: False
  tasks:
  - name: Setup image, flavor, public network and keypair network
    shell: |
      cd /root
      pwd
      source ./keystonerc_admin
      wget http://reposerver/images/CentOS-7-x86_64-GenericCloud.qcow2

      openstack image create \
      --container-format bare --disk-format qcow2 \
      --min-disk 10 --min-ram 1024 --public \
      --file CentOS-7-x86_64-GenericCloud.qcow2 \
      CentOS7

      openstack flavor create --public --id 99 --vcpus 1 --ram 1024 \
      --disk 10 --ephemeral 0 --swap 0 \
      my.standard

      neutron net-create --router:external public
      neutron subnet-create --name public-subnet \
      --allocation-pool start=172.16.100.101,end=172.16.100.104 \
      --disable-dhcp \
      --gateway 172.16.100.254 \
      public 172.16.100.0/24

      openstack keypair create temp-key-1 | tee /root/temp-key-1.pem
      chmod 600 /root/temp-key-1.pem
    args:
      chdir: /root
      creates : /root/temp-key-1.pem
    register: initial_setup_result

  - debug: var=initial_setup_result.stdout_lines

- name: create in-memory inventory
  hosts: localhost
  gather_facts: False
  vars:
    cloud_auth: topse01
    instance_name: ansible-*
  tasks:
  - name: retrieve server information
    os_server_facts: 
      cloud: "{{ cloud_auth }}"
      server: "{{ instance_name }}"
    register: os_setup_result
    ignore_errors: True

  - debug: var=os_setup_result
